version: '3.8'

services:
  app:
    build:
      context: .
    working_dir: /usr/src/app
    env_file:
      - ./dev.env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: